---
- name: Check 'config_volume' parameter
  assert:
    that:
      - "config_volume is defined"
      - "config_volume | length > 0"
    fail_msg: "parameter 'config_volume' is missing"

- name: Check 'data_volume' parameter
  assert:
    that:
      - "data_volume is defined"
      - "data_volume | length > 0"
    fail_msg: "parameter 'data_volume' is missing"

- name: Check 'log_volume' parameter
  assert:
    that:
      - "log_volume is defined"
      - "log_volume | length > 0"
    fail_msg: "parameter 'log_volume' is missing"

- name: Check 'backup_volume' parameter
  assert:
    that:
      - "backup_volume is defined"
      - "backup_volume | length > 0"
    fail_msg: "parameter 'backup_volume' is missing"
