---
- name: Check 'gitlab_config_volume' parameter
  assert:
    that:
      - "gitlab_config_volume is defined"
      - "gitlab_config_volume | length > 0"
    fail_msg: "parameter 'gitlab_config_volume' is missing"

- name: Check 'gitlab_data_volume' parameter
  assert:
    that:
      - "gitlab_data_volume is defined"
      - "gitlab_data_volume | length > 0"
    fail_msg: "parameter 'gitlab_data_volume' is missing"

- name: Check 'gitlab_log_volume' parameter
  assert:
    that:
      - "gitlab_log_volume is defined"
      - "gitlab_log_volume | length > 0"
    fail_msg: "parameter 'gitlab_log_volume' is missing"

- name: Check 'gitlab_backup_volume' parameter
  assert:
    that:
      - "gitlab_backup_volume is defined"
      - "gitlab_backup_volume | length > 0"
    fail_msg: "parameter 'gitlab_backup_volume' is missing"

- name: Check 'gitlab_pages_enabled' parameter
  assert:
    that:
      - "gitlab_pages_enabled is defined"
    fail_msg: "parameter 'gitlab_pages_enabled' is missing"

- name: Check 'gitlab_pages_port' parameter
  assert:
    that:
      - "gitlab_pages_port is defined"
      - "gitlab_pages_port > 0"
      - "gitlab_pages_port < 65536"
    fail_msg: "parameter 'gitlab_pages_port' is missing"
  when: gitlab_pages_enabled is defined
    and gitlab_pages_enabled | bool

- name: Check 'gitlab_pages_external_port' parameter
  assert:
    that:
      - "gitlab_pages_external_port is defined"
      - "gitlab_pages_external_port > 0"
      - "gitlab_pages_external_port < 65536"
    fail_msg: "parameter 'gitlab_pages_external_port' is missing"
  when: gitlab_pages_enabled is defined
    and gitlab_pages_enabled | bool

- name: Check 'gitlab_pages_external_url' parameter
  assert:
    that:
      - "gitlab_pages_external_url is defined"
      - "gitlab_pages_external_url | length > 0"
    fail_msg: "parameter 'gitlab_pages_external_url' is missing"
  when: gitlab_pages_enabled is defined
    and gitlab_pages_enabled | bool
