---
- name: Check 'gitlab_pages_enabled' parameter
  assert:
    that:
      - "gitlab_pages_enabled is defined"
    fail_msg: "parameter 'gitlab_pages_enabled' is missing"

- name: Check 'gitlab_pages_port' parameter
  assert:
    that:
      - "gitlab_pages_port is defined"
      - "gitlab_pages_port | int > 0"
      - "gitlab_pages_port | int < 65536"
    fail_msg: "parameter 'gitlab_pages_port' is missing"
  when: gitlab_pages_enabled is defined
    and gitlab_pages_enabled | bool

- name: Check 'gitlab_pages_external_port' parameter
  assert:
    that:
      - "gitlab_pages_external_port is defined"
      - "gitlab_pages_external_port | int > 0"
      - "gitlab_pages_external_port | int < 65536"
    fail_msg: "parameter 'gitlab_pages_external_port' is missing"
  when: gitlab_pages_enabled is defined
    and gitlab_pages_enabled | bool

- name: Check 'gitlab_pages_external_url' parameter
  assert:
    that:
      - "gitlab_pages_external_url is defined"
      - "gitlab_pages_external_url | length > 0"
    fail_msg: "parameter 'gitlab_pages_external_url' is missing"
  when: gitlab_pages_enabled is defined
    and gitlab_pages_enabled | bool
