---
- name: Create gitlab config directory
  file:
    path: "{{ gitlab_config_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Create gitlab data directory
  file:
    path: "{{ gitlab_data_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create gitlab log directory
  file:
    path: "{{ gitlab_log_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create gitlab backup directory
  file:
    path: "{{ gitlab_backup_volume }}"
    state: directory
    owner: "{{ gitlab_user_id }}"
    group: root
    mode: 0700
