---
- include: check-parameters.yml

- include: install.yml
  when: gitlab_state is not defined or gitlab_state == 'present'

- include: uninstall.yml
  when: gitlab_state is defined and gitlab_state == 'absent'
