---
- include: check-parameters.yml

- name: pull image
  docker_image:
    name: "{{image_name}}:{{image_version}}"
    source: pull
  register: gitlab_image

- include: create-volumes.yml

- name: Setup gitlab config
  template:
    src: gitlab.rb.j2
    dest: "{{config_volume}}/gitlab.rb"
    owner: root
    group: root
    mode: '0600'
  register: gitlab_config

- include: setup-systemd-services.yml

- name: Restart gitlab (on config or image change)
  service:
    name: gitlab
    state: restarted
    enabled: yes
  when: >
    gitlab_config.changed
    or gitlab_service.changed
    or gitlab_image.changed

- name: Start gitlab (if not started already)
  service:
    name: gitlab
    state: started
    enabled: yes
