---
- include: check-parameters.yml

- name: pull image
  docker_image:
    name: "{{ image_name }}:{{ image_version }}"
    source: pull
  notify: Restart gitlab

- include: create-volumes.yml

- name: Setup gitlab config
  template:
    src: gitlab.rb.j2
    dest: "{{ config_volume }}/gitlab.rb"
    owner: root
    group: root
    mode: '0600'
  notify: Restart gitlab

- include: setup-systemd-services.yml

- name: Enable service
  service:
    name: gitlab
    enabled: true
  register: service_state
  changed_when: service_state.status.SubState != 'running'
  notify: Start gitlab service

- name: Flush handlers
  meta: flush_handlers
