---
- include_tasks: check-parameters.yml

- include_tasks: install.yml
  when: gitlab_state is not defined or gitlab_state == 'present'

- include_tasks: uninstall.yml
  when: gitlab_state is defined and gitlab_state == 'absent'
