---
- name: Create gitlab systemd unit file
  template:
    src: gitlab.systemd.j2
    dest: /etc/systemd/system/gitlab.service
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Create gitlab backup service
  template:
    src: gitlab.backup.service.j2
    dest: "/etc/systemd/system/{{ gitlab_backup_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Create gitlab backup timer
  template:
    src: gitlab.backup.timer.j2
    dest: "/etc/systemd/system/{{ gitlab_backup_service_name }}.timer"
    owner: root
    group: root
    mode: 0644
  register: gitlab_backup_timer
  notify: Reload systemd

- name: Enable gitlab service
  service:
    name: gitlab
    enabled: true
  register: service_state
  changed_when: service_state.status.SubState != 'running'
  notify: Start gitlab service
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Enable gitlab backup service
  service:
    name: "{{ gitlab_backup_service_name }}.service"
    enabled: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Enable and start gitlab backup timer
  systemd:
    name: "{{ gitlab_backup_service_name }}.timer"
    state: started
    enabled: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
