Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "192.168.33.71"

  config.vm.provider "virtualbox" do |v|
    v.name = "ansible_gitlab"
    v.memory = 4096
    v.cpus = 2
  end
end
