---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ansible-gitlab-buster
    box: debian/buster64
    memory: 4096
    cpus: 2

provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/converge.yml
    verify: ../shared/vagrant/verify.yml
  inventory:
    host_vars:
      ansible-gitlab-buster:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
