---
- name: Reload systemd
  systemd:
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Start gitlab service
  service:
    name: gitlab
    state: started
  register: gitlab_service_start

- name: Restart gitlab
  service:
    name: gitlab
    state: restarted
  when: not (
    gitlab_service_start is defined
    and gitlab_service_start.changed
    )
    and not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
