---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ansible-gitlab-bionic
    box: ubuntu/bionic64
    memory: 4096
    cpus: 2

provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/converge.yml
    verify: ../shared/vagrant/verify.yml

verifier:
  name: ansible
