---
- name: Converge
  hosts: all
  become: true

  vars:
    gitlab:
      www_port: 10080
      pages_port: 10081
      https_port: 10443
      ssh_port: 10022

  roles:
    - role: ansible-gitlab
      gitlab_image_version: 13.0.6-ce.0
      gitlab_config_volume: /srv/my_gitlab/config
      gitlab_data_volume: /srv/my_gitlab/data
      gitlab_log_volume: /srv/my_gitlab/log
      gitlab_backup_volume: /srv/my_gitlab/backup
      gitlab_external_url: "http://192.168.33.71:{{ gitlab.www_port }}"
      gitlab_ssh_host: localhost
      gitlab_interface: 127.0.0.1
      gitlab_https_port: "{{ gitlab.https_port }}"
      gitlab_http_port: "{{ gitlab.www_port }}"
      gitlab_ssh_port: "{{ gitlab.ssh_port }}"
      gitlab_shell_ssh_port: "{{ gitlab.ssh_port }}"
      gitlab_nginx_disable_hsts: true
      gitlab_pages_enabled: true
      gitlab_pages_external_port: "{{ gitlab.pages_port }}"
      gitlab_pages_external_url: http://192.168.33.71:10081/
      gitlab_email_enabled: true
      gitlab_email_from: 'gitlab@git.myserver.org'
      gitlab_email_display_name: 'gitlab@git.myserver.org'
      gitlab_email_reply_to: 'gitlab@git.myserver.org'
      gitlab_email_subject_suffix: '[Gitlab]'
      gitlab_smtp_address: '127.0.0.1'
      gitlab_smtp_port: 25
      gitlab_smtp_domain: 'git.myserver.org'
      gitlab_smtp_enable_starttls_auto: false
      gitlab_smtp_tls: false
      gitlab_backup_keep_time: 604800
      gitlab_disable_prometheus: true
      gitlab_sidekiq_concurrency: 4
