---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-gitlab
      image_version: 12.9.2-ce.0
      config_volume: /srv/gitlab/config
      data_volume: /srv/gitlab/data
      log_volume: /srv/gitlab/log
      backup_volume: /srv/gitlab/backups
      external_url: http://localhost:10080
      ssh_host: localhost
      https_port: 10443
      http_port: 10080
      ssh_port: 10022
      shell_ssh_port: 10022
      disable_hsts: true
      email:
        enabled: true
        from: 'gitlab@git.myserver.org'
        display_name: 'gitlab@git.myserver.org'
        reply_to: 'gitlab@git.myserver.org'
        subject_suffix: '[Gitlab]'
      smtp:
        address: '127.0.0.1'
        port: 25
        domain: 'git.myserver.org'
        enable_starttls_auto: false
        tls: false
      backup_keep_time: 604800
