---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: should start backup timer
      service:
        name: gitlab-backup.timer
        state: started
      register: backup_timer
      failed_when: backup_timer.changed

    - name: Should GET root site
      get_url:
        url: http://localhost:10080/
        dest: /tmp/root.html
      register: get_request
      retries: 300
      delay: 1
      until: get_request is defined
        and get_request.status_code is defined
        and get_request.status_code == 200

    - name: Should GET pages 404 site
      get_url:
        url: http://localhost:10081/
        dest: /tmp/pages_root.html
      register: get_pages_request
      retries: 300
      delay: 1
      until: get_pages_request is defined
        and get_pages_request.status_code is defined
        and get_pages_request.status_code == 404
      failed_when: false
