---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/default/requirements.yml
    force: true

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: ansible-gitlab-noble
    box: cloud-image/ubuntu-24.04
    memory: 4096
    cpus: 2
  - name: ansible-gitlab-jammy
    box: cloud-image/ubuntu-22.04
    memory: 4096
    cpus: 2
  - name: ansible-gitlab-focal
    box: cloud-image/ubuntu-20.04
    memory: 4096
    cpus: 2
  - name: ansible-gitlab-bookworm
    box: cloud-image/debian-12
    memory: 4096
    cpus: 2
    groups:
      - debian
  - name: ansible-gitlab-bullseye
    box: cloud-image/debian-11
    memory: 4096
    cpus: 2
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../all-parameters/converge.yml
    verify: ../all-parameters/verify.yml

verifier:
  name: ansible
